### ISSUE TITLE
How to avoid a "spam" of containers ?

### ISSUE THREAD

**Issue by JeromeVi** [funkwerk/compose_plantuml#7]
Hi,
I'd like to know if there is a way to delete the container that the command `cat docker-compose.yml | docker run -i funkwerk/compose_plantuml --link-graph | docker run -i think/plantuml > output.svg` creates because each time it creates 2 containers.

Thank you for the help :)

**Comment by lindt** [comment]
`docker run --rm=true` will delete the containers after they exited.
